version: '2.4'
services:
  vscode:
    build:
      context: ./dockerfiles/vscode
    image: ohmymndy/vscode:0.1
    restart: unless-stopped
    environment:
      - DISPLAY=novnc:0.0
    depends_on:
      - novnc
    networks:
      - x11

  novnc:
    image: ohmymndy/novnc:0.1
    restart: unless-stopped
    build:
      .
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=1600
      - DISPLAY_HEIGHT=968
    ports:
      - "8080:8080"
    healthcheck:
      test: timeout 2 curl --connect-timeout 1 --max-time 1 127.0.0.1:6000 &>/dev/null
    networks:
      - x11
networks:
  x11:
