version: '2.4'
services:
  xclock:
    build:
      context: ./dockerfiles/xclock
    image: ohmymndy/xclock:0.1
    init: true
    restart: unless-stopped
    environment:
      - DISPLAY=novnc:0.0
    depends_on:
      - novnc
    networks:
      - x11

  phpstorm-web:
    image: ohmymndy/phpstorm-web:0.1
    build:
      context: ./dockerfiles/novnc/
      target: phpstorm
    init: true
    restart: unless-stopped
    env_file:
      - ./.env
    user: ${PUID:-1000}:${PGID:-1000}
    ports:
      - 8888:8080
    volumes:
      - ./storage/jetbrains:/home/novnc/.config/JetBrains
    healthcheck:
      test: timeout 2 curl --connect-timeout 1 --max-time 1 127.0.0.1:6000 &>/dev/null

  novnc:
    image: ohmymndy/novnc:0.1
    restart: unless-stopped
    init: true
    build:
      context: ./dockerfiles/novnc/
      target: novnc
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=800
      - DISPLAY_HEIGHT=600
    ports:
      - "8080:8080"
    healthcheck:
      test: timeout 2 curl --connect-timeout 1 --max-time 1 127.0.0.1:6000 &>/dev/null
    networks:
      - x11
    env_file:
      - ./.env
networks:
  x11:
    name: x11
